# Generated by Django 4.1.5 on 2024-03-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Fra_JQ', models.URLField(blank=True)),
                ('Beskrivelse', models.TextField()),
                ('Sendt', models.DateField()),
                ('Fra_F_LH', models.URLField(blank=True)),
                ('Beskriv', models.TextField()),
            ],
        ),
    ]
